version: '2'
services:

  front:
    image: leakio/frontend_v10
    ports:
       - "4200:4200"
    depends_on:
       - api-server

  api-server:
    image: edgarslima/apinode-financo
    ports:
      - "80:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6.40
    #image: edgarslima/mysql-financo
    ports:
      - "3306:3306"
    #volumes:
    #  - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: senhacadastro
       MYSQL_USER: root
       MYSQL_DATABASE: financo